# Generated by Django 4.2.4 on 2023-08-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/course_previews/'),
        ),
    ]
