# Generated by Django 4.2.4 on 2023-08-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='starts_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
