# Generated by Django 4.2.4 on 2023-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_ends_at_course_starts_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
