# Generated by Django 4.2.4 on 2023-08-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
