# Generated by Django 4.2.4 on 2023-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer')},
        ),
    ]
