# Generated by Django 4.2.4 on 2023-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_impressions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Too bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
